version: '1.0.{build}'
configuration:
- Debug
- Release
before_build:
- ps: .\dotnet-install.ps1 -Version 1.0.0-preview2-003156
- dotnet restore
build_script:
- dotnet build -c %CONFIGURATION%
test_script:
- dotnet test -c %CONFIGURATION%